eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
server:
  port: 8083
  servlet:
    context-path: /offeredservices

spring:
  application:
    name: ws-vms-offeredservice
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vehicledb
    username: root
    password: pass@word1
offer:
  baseurl: http://ws-vms-offer/offerservices