server:
  port: 8088
  servlet:
    context-path: /offerservices
spring:
  application:
    name: ws-vms-offer
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vehicledb
    username: root
    password: pass@word1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
